import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync } from 'node:crypto';
import { closeSync, existsSync, fsyncSync, mkdirSync, openSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { LicenseEnvelope, LicenseFeature, LicensePlan, MAX_LICENSE_BYTES, createPayload, parseEnvelope, publicKeyFingerprint, signPayload, verifyEnvelope } from './license-contract';
export interface KeyMetadata { keyId: string; algorithm: 'Ed25519'; createdAt: string; publicKeyFingerprintSha256: string; publicKeyPem: string }
export interface IssueRequest { keyPath: string; metadataPath: string; passphrase: string; outputFolder: string; customerName: string; organizationName?: string; installationId: string; plan: LicensePlan; features: LicenseFeature[]; maxDevices: number; notBefore?: string; expiresAt: string | null; operatorNote?: string }
export function assertExternalAuthorityPath(repositoryRoot: string, candidate: string): string { const resolved = path.resolve(candidate); const repo = path.resolve(repositoryRoot); if (resolved === repo || resolved.startsWith(`${repo}${path.sep}`)) throw new Error('PRIVATE_KEY_PATH_INSIDE_REPOSITORY'); if (/([\\/])(OneDrive|Dropbox)([\\/])/i.test(resolved)) throw new Error('CLOUD_SYNC_KEY_PATH_REJECTED'); return resolved; }
function atomicCreate(file: string, content: string | Buffer): void { mkdirSync(path.dirname(file), { recursive: true }); const temporary = `${file}.${process.pid}.tmp`; let descriptor: number | undefined; try { descriptor = openSync(temporary, 'wx', 0o600); writeFileSync(descriptor, content); fsyncSync(descriptor); closeSync(descriptor); descriptor = undefined; if (existsSync(file)) throw new Error('OUTPUT_ALREADY_EXISTS'); renameSync(temporary, file); } finally { if (descriptor !== undefined) closeSync(descriptor); rmSync(temporary, { force: true }); } }
export function generateEncryptedAuthority(input: { repositoryRoot: string; destinationFolder: string; keyId: string; passphrase: string }): { privateKeyPath: string; metadataPath: string; metadata: KeyMetadata } { if (input.passphrase.length < 20) throw new Error('PASSPHRASE_TOO_SHORT'); if (!/^PASKO_LICENSE_KEY_\d{4}_\d{2}$/.test(input.keyId)) throw new Error('INVALID_KEY_ID'); const folder = assertExternalAuthorityPath(input.repositoryRoot, input.destinationFolder); const { privateKey, publicKey } = generateKeyPairSync('ed25519'); const privatePem = privateKey.export({ format: 'pem', type: 'pkcs8', cipher: 'aes-256-cbc', passphrase: input.passphrase }); const publicPem = publicKey.export({ format: 'pem', type: 'spki' }).toString(); const metadata: KeyMetadata = { keyId: input.keyId, algorithm: 'Ed25519', createdAt: new Date().toISOString(), publicKeyFingerprintSha256: publicKeyFingerprint(publicPem), publicKeyPem: publicPem }; const privateKeyPath = path.join(folder, `${input.keyId}.private.pem`); const metadataPath = path.join(folder, `${input.keyId}.public.json`); atomicCreate(privateKeyPath, privatePem); atomicCreate(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`); return { privateKeyPath, metadataPath, metadata }; }
export function readKeyMetadata(file: string): KeyMetadata { const value = JSON.parse(readFileSync(file, 'utf8')) as KeyMetadata; if (!value || value.algorithm !== 'Ed25519' || !value.keyId || publicKeyFingerprint(value.publicKeyPem) !== value.publicKeyFingerprintSha256) throw new Error('INVALID_KEY_METADATA'); return value; }
function safeFilename(value: string): string { return value.normalize('NFKD').replace(/[^A-Za-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'customer'; }
export function issueLicense(repositoryRoot: string, ledgerPath: string, request: IssueRequest, now = new Date()): { file: string; sha256: string; envelope: LicenseEnvelope; duplicateWarning: boolean } {
  const keyPath = assertExternalAuthorityPath(repositoryRoot, request.keyPath); const metadataPath = assertExternalAuthorityPath(repositoryRoot, request.metadataPath); const output = assertExternalAuthorityPath(repositoryRoot, request.outputFolder); const metadata = readKeyMetadata(metadataPath); const encryptedPem = readFileSync(keyPath, 'utf8');
  const derivedPublic = createPublicKey(createPrivateKey({ key: encryptedPem, format: 'pem', passphrase: request.passphrase })).export({ format: 'pem', type: 'spki' }).toString(); if (publicKeyFingerprint(derivedPublic) !== metadata.publicKeyFingerprintSha256) throw new Error('KEY_DOES_NOT_MATCH_METADATA');
  const payload = createPayload({ keyId: metadata.keyId, customerName: request.customerName, organizationName: request.organizationName, installationId: request.installationId, plan: request.plan, features: request.features, maxDevices: request.maxDevices, issuedAt: now, notBefore: request.notBefore ? new Date(request.notBefore) : now, expiresAt: request.expiresAt ? new Date(request.expiresAt) : null }); const envelope = signPayload(payload, encryptedPem, request.passphrase); if (!verifyEnvelope(envelope, metadata.publicKeyPem)) throw new Error('LICENSE_SELF_VERIFICATION_FAILED');
  const text = `${JSON.stringify(envelope, null, 2)}\n`; if (Buffer.byteLength(text, 'utf8') > MAX_LICENSE_BYTES) throw new Error('LICENSE_FILE_TOO_LARGE'); const file = path.join(output, `PASKO-${safeFilename(payload.customerName)}-${payload.plan}-${payload.licenseId.slice(0, 8)}.pasko-license`); atomicCreate(file, text); const sha256 = createHash('sha256').update(text).digest('hex');
  const previous = existsSync(ledgerPath) ? readFileSync(ledgerPath, 'utf8').trim().split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as { installationId?: string }) : []; const duplicateWarning = previous.some((item) => item.installationId === payload.installationId); mkdirSync(path.dirname(ledgerPath), { recursive: true }); const record = { issuedAt: payload.issuedAt, licenseId: payload.licenseId, keyId: payload.keyId, publicKeyFingerprintSha256: metadata.publicKeyFingerprintSha256, customerName: payload.customerName, organizationName: payload.organizationName ?? null, installationId: payload.installationId, plan: payload.plan, notBefore: payload.notBefore, expiresAt: payload.expiresAt, maxDevices: payload.maxDevices, features: payload.features, licenseFileSha256: sha256, operatorNote: request.operatorNote?.trim() || null }; const existing = existsSync(ledgerPath) ? readFileSync(ledgerPath) : Buffer.alloc(0); const ledgerTemp = `${ledgerPath}.${process.pid}.tmp`; writeFileSync(ledgerTemp, Buffer.concat([existing, Buffer.from(`${JSON.stringify(record)}\n`)]), { flag: 'wx', mode: 0o600 }); renameSync(ledgerTemp, ledgerPath); return { file, sha256, envelope, duplicateWarning };
}
export function verifyLicenseFile(file: string, metadataFile: string, installationId?: string): { signatureValid: boolean; installationMatch: boolean | null; envelope: LicenseEnvelope } { const envelope = parseEnvelope(readFileSync(file, 'utf8')); const metadata = readKeyMetadata(metadataFile); return { signatureValid: envelope.payload.keyId === metadata.keyId && verifyEnvelope(envelope, metadata.publicKeyPem), installationMatch: installationId ? envelope.payload.installationId === installationId.trim().toLowerCase() : null, envelope }; }
