import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { generateKeyPairSync } from 'node:crypto';
import { canonicalize, createPayload, normalizeFeatures, normalizeInstallationId, signPayload, verifyEnvelope } from '../dist/license-contract.js';
import { assertExternalAuthorityPath, generateEncryptedAuthority, issueLicense, verifyLicenseFile } from '../dist/authority.js';
import { evaluateLicense, parseLicenseEnvelope } from '../../../apps/desktop/dist/main/license.js';

const installationId='11111111-2222-4333-8444-555555555555';
test('canonicalization is identical to the customer verifier',()=>assert.equal(canonicalize({z:1,a:{d:2,b:[3,1]}}),'{"a":{"b":[3,1],"d":2},"z":1}'));
test('normalizes UUID and deterministic feature order',()=>{assert.equal(normalizeInstallationId(` ${installationId.toUpperCase()} `),installationId);assert.deepEqual(normalizeFeatures(['EXPORT','VOLLEYBALL_CORE']),['VOLLEYBALL_CORE','EXPORT']);assert.throws(()=>normalizeFeatures(['EXPORT','EXPORT']));});
test('issuer output is accepted by exact customer verifier and tampering fails',()=>{const {privateKey,publicKey}=generateKeyPairSync('ed25519');const passphrase='ephemeral-test-passphrase-123';const encrypted=privateKey.export({format:'pem',type:'pkcs8',cipher:'aes-256-cbc',passphrase}).toString();const publicPem=publicKey.export({format:'pem',type:'spki'}).toString();const now=new Date('2026-08-24T12:00:00.000Z');const payload=createPayload({keyId:'TEST_KEY',customerName:'Test Club',installationId,plan:'TRIAL',features:['EXPORT','VOLLEYBALL_CORE'],issuedAt:now,expiresAt:new Date('2026-09-23T12:00:00.000Z')});const envelope=signPayload(payload,encrypted,passphrase);assert.equal(verifyEnvelope(envelope,publicPem),true);assert.equal(evaluateLicense({envelope:parseLicenseEnvelope(JSON.stringify(envelope)),installationId,publicKeys:{TEST_KEY:publicPem},now}).state,'VALID');const tampered=structuredClone(envelope);tampered.payload.plan='PRO';assert.equal(verifyEnvelope(tampered,publicPem),false);assert.equal(evaluateLicense({envelope,installationId:'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',publicKeys:{TEST_KEY:publicPem},now}).state,'WRONG_INSTALLATION');});
test('TRIAL expires, paid perpetual works, future and expired map to client states',()=>{const {privateKey,publicKey}=generateKeyPairSync('ed25519');const passphrase='ephemeral-test-passphrase-123';const encrypted=privateKey.export({format:'pem',type:'pkcs8',cipher:'aes-256-cbc',passphrase}).toString();const publicPem=publicKey.export({format:'pem',type:'spki'}).toString();const now=new Date('2026-08-24T12:00:00.000Z');assert.throws(()=>createPayload({keyId:'K',customerName:'X',installationId,plan:'TRIAL',features:[],issuedAt:now,expiresAt:null}));for(const [issuedAt,notBefore,expiresAt,expected] of [[new Date('2026-08-01T12:00:00.000Z'),new Date('2026-08-01T12:00:00.000Z'),new Date('2026-08-23T12:00:00.000Z'),'EXPIRED'],[now,new Date('2026-08-25T12:00:00.000Z'),new Date('2026-09-25T12:00:00.000Z'),'NOT_YET_VALID'],[now,now,null,'VALID']]){const payload=createPayload({keyId:'K',customerName:'X',installationId,plan:'PRO',features:[],issuedAt,notBefore,expiresAt});const envelope=signPayload(payload,encrypted,passphrase);assert.equal(evaluateLicense({envelope,installationId,publicKeys:{K:publicPem},now}).state,expected)}});
test('atomic issuance, verification, ledger and duplicate warning use external ephemeral keys',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'pasko-issuer-test-'));try{const authority=path.join(root,'authority');const output=path.join(root,'output');const ledger=path.join(root,'ledger','issuer.jsonl');const passphrase='ephemeral-test-passphrase-123';const key=generateEncryptedAuthority({repositoryRoot:path.join(root,'repository'),destinationFolder:authority,keyId:'PASKO_LICENSE_KEY_2099_01',passphrase});const request={keyPath:key.privateKeyPath,metadataPath:key.metadataPath,passphrase,outputFolder:output,customerName:'Synthetic Club',installationId,plan:'TRIAL',features:['VOLLEYBALL_CORE','EXPORT'],maxDevices:1,expiresAt:'2026-09-23T12:00:00.000Z'};const first=issueLicense(path.join(root,'repository'),ledger,request,new Date('2026-08-24T12:00:00.000Z'));assert.equal(first.duplicateWarning,false);assert.equal(verifyLicenseFile(first.file,key.metadataPath,installationId).signatureValid,true);const second=issueLicense(path.join(root,'repository'),ledger,request,new Date('2026-08-24T12:01:00.000Z'));assert.equal(second.duplicateWarning,true);assert.notEqual(first.envelope.payload.licenseId,second.envelope.payload.licenseId);assert.equal((await readFile(ledger,'utf8')).trim().split(/\r?\n/).length,2);assert.rejects(readFile(`${first.file}.${process.pid}.tmp`));}finally{await rm(root,{recursive:true,force:true})}});
test('authority path guard rejects repository and cloud-sync locations',()=>{assert.throws(()=>assertExternalAuthorityPath('C:/repo','C:/repo/keys'));assert.throws(()=>assertExternalAuthorityPath('C:/repo','C:/Users/Test/OneDrive/keys'));assert.equal(assertExternalAuthorityPath('C:/repo','D:/offline-keys'),path.resolve('D:/offline-keys'));});
test('wrong passphrase and wrong metadata leave no license or ledger',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'pasko-issuer-wrong-'));try{const key=generateEncryptedAuthority({repositoryRoot:path.join(root,'repo'),destinationFolder:path.join(root,'keys'),keyId:'PASKO_LICENSE_KEY_2099_02',passphrase:'ephemeral-test-passphrase-123'});assert.throws(()=>issueLicense(path.join(root,'repo'),path.join(root,'ledger.jsonl'),{keyPath:key.privateKeyPath,metadataPath:key.metadataPath,passphrase:'wrong-password-value-123',outputFolder:path.join(root,'out'),customerName:'X',installationId,plan:'PRO',features:[],maxDevices:1,expiresAt:null}));}finally{await rm(root,{recursive:true,force:true})}});
